# Generated by Django 3.2 on 2021-04-10 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
                ('response_time', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusions', models.CharField(blank=True, max_length=255, null=True)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_tracker.actioneffect')),
                ('searcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_tracker.actionstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action_tracker.actiontype')),
            ],
        ),
    ]
